# Generated by Django 2.1.2 on 2018-12-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analyze_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Analyze name')),
                ('module_name', models.CharField(max_length=255, verbose_name='Analyze module name')),
            ],
            options={
                'db_table': 'analyze_type',
            },
        ),
        migrations.CreateModel(
            name='category_child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Child Categories')),
            ],
            options={
                'db_table': 'category_child',
            },
        ),
        migrations.CreateModel(
            name='category_parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Parent Categories')),
            ],
            options={
                'db_table': 'category_parent',
            },
        ),
        migrations.CreateModel(
            name='data_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Data name')),
                ('ip', models.CharField(max_length=255, verbose_name='ip')),
                ('kimlik', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kimlik')),
            ],
            options={
                'db_table': 'data_source',
            },
        ),
        migrations.CreateModel(
            name='sensor_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=255, verbose_name='key_word')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='home.category_child')),
                ('ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_source', to='home.data_source')),
            ],
            options={
                'db_table': 'sensor_name',
            },
        ),
        migrations.AddField(
            model_name='category_child',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='home.category_parent'),
        ),
    ]
